# mapping of country names
mapping = {
    'Bolivia, Plurinational State of': 'Bolivia',
    'Brunei Darussalam': 'Brunei',
    'Czech Republic': 'Czechia',
    'Congo': 'Congo Republic',
    'Congo, Democratic Republic of the': 'DR Congo',
    'Côte d\'Ivoire': 'Ivory Coast',
    'Gambia': 'The Gambia',
    'Hong Kong, China': 'Hong Kong',
    'Iran, Islamic Republic of': 'Iran',
    'Korea, Democratic People\'s Republic of': 'North Korea',
    'Korea, Republic of': 'South Korea',
    'Lao People\'s Democratic Republic': 'Laos',
    'Macao, China': 'Macao',
    'Micronesia, Federated States of': 'Micronesia',
    'Moldova, Republic of': 'Moldova',
    'Reunion': 'Réunion',
    'Russian Federation': 'Russia',
    'Saint Kitts and Nevis': 'St Kitts and Nevis',
    'Saint Vincent and the Grenadines': 'St Vincent and Grenadines',
    'Sao Tome and Principe': 'São Tomé and Príncipe',
    'State of Palestine': 'Palestine',
    'Syrian Arab Republic': 'Syria',
    'Taiwan Province of China': 'Taiwan',
    'United Republic of Tanzania': 'Tanzania',
    'Venezuela, Bolivarian Republic of': 'Venezuela',
    'Viet Nam': 'Vietnam',
}
